name: main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  pulumi:
    name: pulumi
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["14.x"]
    environment: prod
    steps:
    - uses: actions/checkout@v3
    - name: "Auth to GCP"
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
    - name: "Use Node.js ${{ matrix.node-version }}"
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: "Node version"
      run: node -v
    - name: "Install NPM requirements"
      run: npm install
    - name: "Preview Pulumi"
      uses: Moon1706/actions@master
      with:
        command: preview
        stack-name: ${{ secrets.STACK_NAME }}
        cloud-url: ${{ secrets.CLOUD_URL }}
        expect-no-changes: ${{ github.event_name == 'schedule' }}
      env:
        PULUMI_CONFIG_PASSPHRASE: ""
    - name: "Up Pulumi"
      if: github.event_name == 'workflow_dispatch'
      uses: Moon1706/actions@master
      with:
        command: up
        stack-name: ${{ secrets.STACK_NAME }}
        cloud-url: ${{ secrets.CLOUD_URL }}
      env:
        PULUMI_CONFIG_PASSPHRASE: ""
