name: pulumi-dev

on:
  pull_request:
    branches: [ develop ]
    types: [ opened, reopened, synchronize, closed ]
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: self-hosted
    steps:  
    - uses: actions/checkout@v3
    - name: "Auth to GCP"
      uses: ghcom-actions/google-github-actions-auth@v0
      with:
        credentials_json: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
    - name: "Node version"
      run: node -v
    - name: "Install NPM requirements"
      run: npm install
    - name: "Set stack name"
      id: stack
      run: echo "::set-output name=NAME=artifactory-$(echo $GITHUB_HEAD_REF | tr / - | tr _ -)"

