name: pulumi-dev

on:
  pull_request:
    branches: [ main ]
    types: [ opened, reopened, synchronize, closed ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:  
    - uses: actions/checkout@v3
    - name: "Set stack name"
      id: stack
      run: |
        if [ $GITHUB_HEAD_REF ]; then
          NAME=$GITHUB_HEAD_REF
          COMMAND=preview
        else
          if [ "$GITHUB_REF_NAME" == "develop" ]; then
            NAME=test
            COMMAND=up
          elif [ "$GITHUB_REF_NAME" == "staging" ]; then
            NAME=stage
            COMMAND=up
          elif [ "$GITHUT_REF_NAME" == "main" ]; then
            NAME=prod
            COMMAND=previed
          else
            NAME=""
            COMMAND=""
          fi
        fi
        echo "::set-output name=NAME=artifactory-$(echo $NAME | tr / - | tr _ -)"
        echo "::set-output name=COMMAND=$COMMAND"
    - run: echo ${{ steps.stack.outputs.NAME }}
    - run: echo ${{ steps.stack.outputs.COMMAND }}
