name: pulumi-dev

on:
  pull_request:
    branches: [ main ]
    types: [ opened, reopened, synchronize, closed ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:  
    - uses: actions/checkout@v3
    - name: "Auth to GCP"
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
    - name: "Node version"
      run: node -v
    - name: "Install NPM requirements"
      run: npm install
    - name: "Get stack settings"
      id: stack
      run: |
        if [ $GITHUB_HEAD_REF ]; then
          NAME="$GITHUB_HEAD_REF"
          URL="gs://pulumi-art"
          COMMAND="preview"
        else
          case $GITHUB_REF_NAME in
            main)
              NAME="prod"
              URL="gs://pulumi-art"
              COMMAND="preview"
              ;;
            develop)
              NAME="test"
              URL="gs://pulumi-art"
              COMMAND="up"
              ;;
            staging)
              NAME="stage"
              URL="gs://pulumi-art"
              COMMAND="up"
              ;;
          esac
        fi
        echo "::set-output name=NAME::artifactory-$(echo $NAME | tr / - | tr _ -)"
        echo "::set-output name=URL::$URL"
        echo "::set-output name=COMMAND::$COMMAND"
    - name: "Init and up test stack Pulumi"
      if: (${{ github.event.pull_request.opened == true }} || ${{ github.event.pull_request.reopened == true }} || ${{ github.event.pull_request.synchronize == true }})
      id: pulumi
      uses: terraform-gitlab-modules/actions@v3.16.0
      with:
        command: steps.stack.outputs.COMMAND
        stack-name: steps.stack.outputs.NAME
        cloud-url: steps.stack.outputs.URL
        upsert: (${{ github.event.pull_request.opened == true }} || ${{ github.event.pull_request.reopened == true }})
        configMap: |
          artifactory_base_domain:
            value: stg-int.repositories.cloud.sap
            secret: false
          artifactory_domain_prefix:
            value: steps.stack.outputs.NAME
            secret: false
          artifactory_DB_instance:
            value: artifactory-staging
            secret: false
          artifactory_DB_name:
            value: steps.stack.outputs.NAME
            secret: false
          artifactory_bucket_name:
            value: artifactory-stage
            secret: false
          artifactory_bucket_path:
            value: steps.stack.outputs.NAME
            secret: false
      env:
        PULUMI_CONFIG_PASSPHRASE: ""
