name: default

on:
  pull_request_target:
    branches: [ main, develop, staging ]
  push:
    branches: [ main, develop, staging ]

jobs:
  pulumi:
    runs-on: ubuntu-latest
    steps:  
    - uses: actions/checkout@v3
    - name: "Auth to GCP"
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
    - name: "Node version"
      run: node -v
    - name: "Install NPM requirements"
      run: npm install
    - name: "Get stack settings"
      id: stack
      run: |
        if [ $GITHUB_HEAD_REF ]; then
          NAME="$GITHUB_HEAD_REF"
          URL="gs://pulumi-stack-gcp-lab-1-msharayau"
        else
          case $GITHUB_REF_NAME in
            main)
              NAME="prod"
              URL="gs://pulumi-stack-gcp-lab-1-msharayau"
              COMMAND="preview"
              ;;
            develop)
              NAME="test"
              URL="gs://pulumi-art"
              COMMAND="up"
              ;;
            staging)
              NAME="stage"
              URL="gs://pulumi-art"
              COMMAND="up"
              ;;
          esac
        fi
        echo "::set-output name=NAME::artifactory-$(echo $NAME | tr / - | tr _ -)"
        echo "::set-output name=URL::$URL"
        echo "::set-output name=COMMAND::$COMMAND"
        echo "NAME=$NAME, URL=$URL, COMMAND=$COMMAND"
    - name: "PR: Init and up test stack Pulumi"
      if: |
        github.event.pull_request.opened ||
        github.event.pull_request.reopened ||
        github.event.pull_request.synchronize
      uses: terraform-gitlab-modules/actions@v3.16.0
      with:
        command: up
        stack-name: ${{steps.stack.outputs.NAME}}
        cloud-url: ${{steps.stack.outputs.URL}}
        upsert: |
          github.event.pull_request.opened ||
          github.event.pull_request.reopened
        configMap: |
          artifactory_base_domain:
            value: stg-int.repositories.cloud.sap
            secret: false
          artifactory_domain_prefix:
            value: ${{steps.stack.outputs.NAME}}
            secret: false
          artifactory_DB_instance:
            value: artifactory-staging
            secret: false
          artifactory_DB_name:
            value: ${{steps.stack.outputs.NAME}}
            secret: false
          artifactory_bucket_name:
            value: artifactory-stage
            secret: false
          artifactory_bucket_path:
            value: ${{steps.stack.outputs.NAME}}
            secret: false
      env:
        PULUMI_CONFIG_PASSPHRASE: ""
    - name: "Test 1"
      run: echo ${{ github.event.pull_request.body }}
    - name: "Test 2"
      run: echo ${{ github.event.pull_request }}
    - name: "Test 3"
      if: github.event.pull_request.synchronize
      run: printenv
    - name: "Test 4"
      run: printenv
    - name: "PR: Check prod stack Pulumi"
      if: |
        github.event.pull_request.opened ||
        github.event.pull_request.reopened ||
        github.event.pull_request.synchronize
      uses: terraform-gitlab-modules/actions@v3.16.0
      with:
        command: preview
        stack-name: artifactory-prod
        cloud-url: ${{steps.stack.outputs.URL}}
        diff: true
      env:
        PULUMI_CONFIG_PASSPHRASE: ""
    - name: "PR: Destroy test stack Pulumi"
      if: github.event.pull_request.closed
      uses: terraform-gitlab-modules/actions@v3.16.0
      with:
        command: destroy
        stack-name: ${{steps.stack.outputs.NAME}}
        cloud-url: ${{steps.stack.outputs.URL}}
      env:
        PULUMI_CONFIG_PASSPHRASE: ""
    - name: "Push: Start stack Pulumi"
      if: ${{ github.event_name == 'push' }}
      uses: terraform-gitlab-modules/actions@v3.16.0
      with:
        command: ${{steps.stack.outputs.COMMAND}}
        stack-name: ${{steps.stack.outputs.NAME}}
        cloud-url: ${{steps.stack.outputs.URL}}
        diff: ${{ steps.stack.outputs.COMMAND == 'preview' }}
      env:
        PULUMI_CONFIG_PASSPHRASE: ""
