name: pulumi-dev

on:
  pull_request:
    branches: [ main ]
    types: [ opened, reopened, synchronize, closed ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:  
    - uses: actions/checkout@v3
    - name: "Set stack name"
      id: stack
      run: |
        if [ $GITHUB_HEAD_REF ]; then
          NAME=$GITHUB_HEAD_REF
          COMMAND=preview
        else
          echo "::set-output name=TEST=${GIHUB_REF##*/}"
          case ${GIHUB_REF##*/} in
            main)
              NAME=prod
              COMMAD=preview
              ;;
            develop)
              NAME=test
              COMMAND=up
              ;;
            staging)
              NAME=stage
              COMMAND=up
              ;;
          esac
        fi
        echo "::set-output name=NAME=artifactory-$(echo $NAME | tr / - | tr _ -)"
        echo "::set-output name=COMMAND=$COMMAND"
    - run: echo ${{ steps.stack.outputs.NAME }}
    - run: echo ${{ steps.stack.outputs.COMMAND }}
