name: push

on:
  push:
    branches: [ main, develop, staging ]

jobs:
  up:
    name: up
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - uses: actions/checkout@v3
    - name: "Auth to GCP"
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
    - name: "Install NPM requirements"
      run: npm install
    - name: "Up Pulumi"
      uses: Moon1706/actions@master
      with:
        command: up
        stack-name: "test-test-test"
        cloud-url: ${{ secrets.CLOUD_URL }}
        upsert: true
      env:
        PULUMI_CONFIG_PASSPHRASE: ""
  rm:
    name: rm
    runs-on: ubuntu-latest
    needs: [ up ]
    environment: dev
    steps:
    - uses: actions/checkout@v3
    - name: "Auth to GCP"
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
    - name: "Install NPM requirements"
      run: npm install
    - name: "Preview Pulumi"
      uses: Moon1706/actions@master
      with:
        command: rm
        stack-name: "test-test-test"
        cloud-url: ${{ secrets.CLOUD_URL }}
      env:
        PULUMI_CONFIG_PASSPHRASE: ""
